import randomColor from "randomcolor";

export const colors = [
  { key: "DAI", color: "#FAC146" },
  { key: "WETH", color: "#c71a67" },
  { key: "ETH", color: "#6f7bba" },
  { key: "ARB", color: "#1569a1" },
  { key: "AVAX", color: "#e84142" },
  { key: "FTM", color: "#1969ff" },
  { key: "OP", color: "#ff0420" },
  { key: "ALCX", color: "#deaf8f" },
  { key: "FXS", color: "#000000" },
  { key: "MTA", color: "#ffffff" },
  { key: "LDO", color: "#2fb1eb" },
  { key: "BADGER", color: "#f3a52c" },
  { key: "CRV", color: "#3465A4" },
  { key: "CVX", color: "#7c7c7c" },
  { key: "EURS", color: "#2c74ed" },
  { key: "TRIBE", color: "#178dd0" },
  { key: "OGN", color: "#1b85fc" },
  { key: "LUNA", color: "#df3e35" },
  { key: "YFI", color: "#0556f9" },
  { key: "MATIC", color: "#8247e5" },
  { key: "RAI", color: "#96e5d6" },
  { key: "FLX", color: "#7adaca" },
  { key: "T", color: "#02bd31" },
  { key: "UST", color: "#e58f90" },
  { key: "GRO", color: "#aa65df" },
  { key: "LFT", color: "#5da5d8" },
  { key: "SNX", color: "#00d1ff" },
  { key: "INV", color: "#6781c1" },
  { key: "LYRA", color: "#48e29f" },
  { key: "STG", color: "#ededee" },
  { key: "JPEG", color: "#b4f8df" },
  { key: "USDN", color: "#2562f6" },
  { key: "GNO", color: "#a4a9af" },
  { key: "TUSD", color: "#1a59fd" },
  { key: "USDD", color: "#23705c" },
  { key: "FRAX", color: "#000000" },
  { key: "USDC", color: "#2775ca" },
  { key: "USDT", color: "#52b095" },
  { key: "CNC", color: "#4BDBB3" },
  { key: "mim", color: "#fe88b1" },
  { key: "pax", color: "#56569b" },
  { key: "Aave", color: "#36b2c3" },
  { key: "GUSD", color: "#f89c74" },
  { key: "OUSD", color: "#f6cf71" },
  { key: "bean", color: "#3eb94e" },
  { key: "lusd", color: "#745ddf" },
  { key: "seth", color: "#c9db74" },
  { key: "susd", color: "#443d5d" },
  { key: "3pool", color: "#F504D3" },
  { key: "alusd", color: "#d3b484" },
  { key: "steth", color: "#f2b701" },
  { key: "busdv2", color: "#56569b" },
  { key: "crveth", color: "#af82ff" },
  { key: "cvxeth", color: "#2f8ac4" },
  { key: "eurusd", color: "#e68310" },
  { key: "fraxbp", color: "#8be0a4" },
  { key: "frxeth", color: "#e68310" },
  {
    key: "Uniswap",
    color: "#ff007a",
  },
  {
    key: "Kyber",
    color: "#33ca9d",
  },
  {
    key: "Curvefi",
    color: "#3465A4",
  },
  {
    key: "Sushi",
    color: "#fc6bd7",
  },
  {
    key: "Pancakeswap",
    color: "#53dee9",
  },
  {
    key: "Balancer",
    color: "#09213c",
  },
  {
    key: "Saddle",
    color: "#65b0a9",
  },
  {
    key: "Clipper",
    color: "#e4c662",
  },
  {
    key: "Shibaswap",
    color: "#ffa409",
  },
  {
    key: "Hashflow",
    color: "#171b21",
  },
  {
    key: "Aave",
    color: "#B6509E",
  },
  {
    key: "compound",
    color: "#00d395",
  },
  {
    key: "Ironbank",
    color: "#1fa647",
  },
  {
    key: "Silo",
    color: "#171717",
  },
  {
    key: "Uwulend",
    color: "#5959ff",
  },
  { key: "CNC/ETH", color: "#ed645a" },
  { key: "LDO_ETH", color: "#909091" },
  { key: "YFI/ETH", color: "#24796c" },
  { key: "3EURpool", color: "#ac29fb" },
  { key: "CLEV/ETH", color: "#f4603e" },
  { key: "FPI2Pool", color: "#4343a1" },
  { key: "KP3R/ETH", color: "#a5aa99" },
  { key: "STG/USDC", color: "#DE2D02" }, //
  { key: "eCFX/ETH", color: "#b3b3b3" },
  { key: "frax3crv", color: "#ffea4a" },
  { key: "DCHF/3CRV", color: "#dcb0f2" },
  { key: "STBT/3CRV", color: "#99c945" },
  { key: "USDD/3CRV", color: "#2f8ac4" },
  { key: "cbETH/ETH", color: "#87c55f" },
  { key: "pxCVX/CVX", color: "#909090" },
  { key: "3CRV/lvUSD", color: "#764e9f" },
  { key: "BTRFLY/ETH", color: "#52bca3" },
  { key: "GUSDFRAXBP", color: "#cc3a8e" },
  { key: "LUSDFRAXBP", color: "#ffc365" },
  { key: "OHM/FRAXBP", color: "#764e9f" },
  { key: "TUSDFRAXBP", color: "#24796c" },
  { key: "XAI/FRAXBP", color: "#4343a1" },
  { key: "cvxCrv/Crv", color: "#f6cf71" },
  { key: "cvxFxs/Fxs", color: "#99c945" },
  { key: "tricrypto2", color: "#FF8E00" }, //
  { key: "DOLA/FRAXBP", color: "#b497e7" },
  { key: "alusdfraxbp", color: "#cc61b0" },
  { key: "eUSD+FRAXBP", color: "#66c5cc" },
  { key: "STG/FRAX-USDC", color: "#9eb9f3" },
  { key: "clevUSDFRAXBP", color: "#ed645a" },
  { key: "PAIR_ETH_MATIC", color: "#ffaf32" },
  { key: "bLUSD_LUSD3CRV", color: "#f4603e" },
  { key: "stETH concentrated", color: "#5d69b1" },
  { key: "Paxos Dollar (USDP)", color: "#87c55f" },
  { key: "rockethpool rETH/ETH", color: "#cc61b0" },
  { key: "other", color: randomColor({ seed: "other" }) },
];
